repos:
- repo: https://github.com/PyCQA/pylint
  rev: v3.1.0
  hooks:
    - id: pylint
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1 # Use the correct version
    hooks:
    -   id: autopep8
-   repo: https://github.com/psf/black
    rev: 21.9b0 # Use the correct version of Black
    hooks:
    -   id: black
