[tool.pre-commit-hooks]
repos = [
    { repo = "https://github.com/pre-commit/pre-commit-hooks", rev = "v4.0.1", hooks = [{ id = "autopep8" }] }
]

[tool.autopep8]
max_line_length = 120
ignore = ["E501", "W6"]
in-place = true
recursive = true
aggressive = 3
experimental = true
exclude = ["*.pyi", "build/*", "dist/*"]
